name: N-Omar-Trial-Linking-With-GH-approved
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR approval status
        if: github.event.review.state == 'APPROVED'
        run: echo "This PR was approved"
      - name: Check PR rejection status
        if: github.event.review.state != 'APPROVED'
        run: echo "This PR was declined"
